name: Python Sort CI

on:
  push:
    branches: [ "master"]

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"         

      - name: Run Python Sort script
        run: |
          python python/sort.py          
